name: Go 项目自动构建

on:
  push:
    branches:
      - main  # 推送到 main 分支时触发
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出源码
      - name: 检出代码
        uses: actions/checkout@v3

      # 2. 设置 Go 版本（可修改为你项目所用版本）
      - name: 设置 Go 环境
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # 可根据需要改成你的 Go 版本

      # 3. 编译 Go 项目，输出为 mapproject
      - name: 编译项目
        run: |
          go mod tidy  # 如果使用了 go.mod
          go build -o mapproject main.go  # 修改为你的主入口文件

      # 4. 可选：上传构建产物（供下载）
      - name: 上传构建结果
        uses: actions/upload-artifact@v3.1.3
        with:
          name: mapproject-binary
          path: mapproject
