# 文件路径：.github/workflows/build.yml
name: Go + HTML 项目自动构建

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出仓库代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Go 环境（假设使用 Go 1.20）
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      # 3. 确保依赖一致（如果使用 go.mod）
      - name: Tidy modules
        run: go mod tidy

      # 4. 编译项目，生成 mapproject 可执行文件
      - name: Build mapproject
        run: go build -o mapproject main.go

      # 5. 上传编译产物，注意必须用 @v4
      - name: Upload build artifact
        uses: actions/upload-artifact@v4   # 必须使用 @v4，否则报错“Missing download info”
        with:
          name: mapproject-binary
          path: mapproject
